<!DOCTYPE html>
<html lang=en-GB>
<head>
<title>Exceptions Page</title>
<!-- Styling. -->
<!-- The following href is blank, but will be populated once the
DOM is fully loaded. -->
<link id="css" rel="stylesheet" type="text/css" href=""><script src="/scripts/style.js"></script>
<!-- The following are used for stying code. -->
<script src="/tools/highlight/highlight.min.js"></script>
<script>hljs.highlightAll();</script>
<link id="code_theme" rel="stylesheet" type="text/css" href="">
<!-- Styling. -->
<script src="/scripts/style.js"></script>
<!-- The following are used for stying code. -->
<script src="/tools/highlight/highlight.min.js"></script>
<script>hljs.highlightAll();</script>
<!-- The following href should be set when the DOM is loaded. -->
<link id="css1" rel="stylesheet" type="text/css" href="">
<link id="css2" rel="stylesheet" type="text/css" href="">
</head>
<body>
<header>
<button id="style_button" onclick="swapStyle()"></button>
<div>
<nav>
<a id="home" class="nav" href="../home/index.html">Home</a> <a id="programming" class="nav" href="../programming/index.html">Programming</a> <a id="python" class="nav" href="../python/index.html">Python</a> <a id="variables" class="nav" href="../variables/index.html">Variables</a> <a id="github" class="nav" href="../github/index.html">GitHub</a> <a id="abm1" class="nav" href="../abm1/index.html">ABM1</a> <a id="containers" class="nav" href="../containers/index.html">Containers</a> <a id="branching" class="nav" href="../branching/index.html">Branching</a> <a id="loops" class="nav" href="../loops/index.html">Loops</a> <a id="abm2" class="nav" href="../abm2/index.html">ABM2</a> <a id="functions" class="nav" href="../functions/index.html">Functions</a> <a id="abm3" class="nav" href="../abm3/index.html">ABM3</a> <a id="classes" class="nav" href="../classes/index.html">Classes</a> <a id="abm4" class="nav" href="../abm4/index.html">ABM4</a> <a id="io" class="nav" href="../io/index.html">IO</a> <a id="abm5" class="nav" href="../abm5/index.html">ABM5</a> <a id="modules" class="nav" href="../modules/index.html">Modules</a> <a id="abm6" class="nav" href="../abm6/index.html">ABM6</a> <a id="exceptions" class="nav" href="../exceptions/index.html">Exceptions</a> <a id="abm7" class="nav" href="../abm7/index.html">ABM7</a> <a id="gui" class="nav" href="../gui/index.html">GUI</a> <a id="abm8" class="nav" href="../abm8/index.html">ABM8</a> <a id="web" class="nav" href="../web/index.html">Web</a> <a id="abm9" class="nav" href="../abm9/index.html">ABM9</a> <a id="assignments" class="nav" href="../assignments/index.html">Assignments</a> <a id="index" class="nav" href="../index/index.html">Index</a> <a id="references" class="nav" href="../references/index.html">References</a>
</nav>
</div>
</header>
<div>
<h1>Exceptions</h1>
<h2 id="1">1. Introduction</h2>
<p>When the Python interpretter encounters a problem - a error, it
generates an Exception object which can be interrogated to try to
understand what the problem is.</p>
<p>In this part of the course we will learn a bit about exception
handling and debugging.</p>

<h2 id="2">2. Try-Except</h2>
<p>If it is suspected that code might generate an exception, a
try-except compound statement can be used.</p>
<p>Consider the following example:</p>
<pre><code class="language-python"># Catch an excpetion
import random
try:
    a = 1/random.random()
    # Random generates number in
    # range 0,1 so
    # ZeroDivisionError possible
except:
    a = 0
print("Done")</code></pre>
<p>This will run the try clause of the compound statement, and if
an exception is raised in running that, then and only then will it
run the except clause.</p>
<p>The except clause in the example above catches any exception
type. It is possible to be more specific and catch particular
types of exception, for example, the following example will only
run the except cluase if the exception thrown is a
ZeroDivisionError:</p>
<pre><code class="language-python"># Catch a specific exception:
import random
try:
    a = 1/random.random()
    # Random generates number in
    # range 0,1 so
    # ZeroDivisionError possible
except ZeroDivisionError :
    a = 0
print("Done")</code></pre>
<p>There is a heirarchy of exception types. For details see:
<a href="https://docs.python.org/3/library/exceptions.html#Exception">
Python Exceptions</a>.</p>
<p>If an exception is encountered and is not of the type handled
by an except clause, it is raised to where the code that raised
the exception was called from. This raising continues until there
is exception handling or until the exception reaches the top level
when the program exits and a stacktrace error message (which lists
exception raising details) is printed.</p>
<p>More than one type of exception can be handled simultaneously
in a couple of ways:</p>
<ol>
<li>The except clause can contain a tuple of types, for example:
<pre><code class="language-python">import random
try:
    a = 1/random.random()
except (ZeroDivisionError, SystemError) :
    a = 0
print("Done")</code></pre></li>
<li>Using multiple except clauses, for example:
<pre><code class="language-python">import random
try:
    a = 1/random.random()
except (ZeroDivisionError, SystemError) :
    a = 0
print("Done")</code></pre></li>
</ol>

<h2 id="3">3. Raising Exceptions</h2>
<p>Exceptions are raised automatically if they are encountered and
there no Try-Expect statement catches them.</p>
<p>The Raise Keyword (raise) used inside an except clause, raises
the exception. This is useful as temporarily catching the
exception can help provide diagnostics and with debugging.</p>
<p>The user can raise exceptions, for example, the following code
raises a ZeroDivisionError exception:</p>
<pre><code class="language-python">a = random.random()
if a == 0:
    raise ZeroDivisionError
else:
    a = 1/a</code></pre>
<p>You can define your own exceptions by subclassing an
exception.</p>

<h2 id="4">4. Else and Finally</h2>
<p>If there is something that should be run only if exceptions are
not raised, the add an Else Clause (else) to the Try-Except, for
example:</p>
<pre><code class="language-python">import random
try:
    a = 1/random.random()
except:
    a = 0
else:
    print(a)
    # Exceptions here not caught.
print("Done")</code></pre>
<p>If there is something that should be run, whether an exception
is raised or not, then add a Finally Clause (finally) to the
Try-Except, for example:</p>
<pre><code class="language-python">import random
try:
    a = 1/random.random()
except:
    a = 0
finally:
    if a == None:
        a = -1
print("Done")</code></pre>
<p>In executing the finally clause, any exceptions encountered are
saved, to be re-raised after the finally has run. Finally clauses
are always executed, even if there is a Return Statement (return)
in the try or except clauses.<p>
<p>Exceptions raised in executing the finally clause are nested
within the prior saved exception.</p>
<p>Break and return statements within a finally clause will delete
the saved exception.</p>
<p>If the Try-Except compound statement is in a loop, then the
Continue Keyword (continue) can be used to execute the finally
clause before restarting the loop, and the Break Keyword (break)
can be used to execute the finally clause.</p>

<h2 id="5">5. System Exit Calls</h2>
<p>To exit the system at any point, call the Exit Function (exit)
from the Sys Module (sys). For example:</p>
<pre><code class="language-python">import sys
sys.exit()</code></pre>
<p>This has an arg option:</p>
<pre><code class="language-python">sys.exit(arg)</code></pre>
<p>Where arg is a number that the system will report. Zero is
usually regarded as exiting with no issues.</p>
<p>For more on this, see:
<a href="https://docs.python.org/3/library/sys.html#sys.exit">
sys.exit</a>.
See also:
<a href="https://docs.python.org/3/library/errno.html">errno</a> -
a special module on system error codes.</p>

</div>
<footer>
<div>
<p><a id="next" class="nav" href="../abm7/index.html">Next: ABM7</a></p>
</div>
<p>Date last modified: 2023-02-27.</p>
<p><a href="https://creativecommons.org/share-your-work/public-domain/cc0/">CC0 Licence</a></p>
</footer>
</body>
</html>
